### ISSUE TITLE
403 error again

### ISSUE THREAD

**Issue by gregoryh325** [yuliskov/SmartTube#3789]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

Beta 22.77 and stable 22.74

### Device Type

Smart TV/Box

### Affected Android

Android TV 11

### Steps to reproduce the bug

403 error started again today on stable and beta latest versions

### Additional information

Video never starts then 403 error popup

**Comment by reyzor-q** [comment]
Same issue here

**Comment by AnthonyA1223** [comment]
Same, casting from my phone to smartTube works though, using that as a workaround.

**Comment by ubiquitas** [comment]
me too. On 22.74 Nvidia Shield

**Comment by LimesKey** [comment]
same

**Comment by Shadowmaster16** [comment]
It works fine. Start a new video and wait. The program tried different methods by itself. After 4-5 attempts, it played the video. Later, it worked without testing and chose the right playback method.

**Comment by therealdrl** [comment]
> It works fine. Start a new video and wait. The program tried different methods by itself. After 4-5 attempts, it played the video. Later, it worked without testing and chose the right playback method.

100% accurate. Open a video, then put the remote down and wait. Don't back out. It'll spinwheel 4-5 times in succession and throw up the 403 error a few times, then load the video.

**Comment by ubiquitas** [comment]
thanks, seems patience is key - works for me too

**Comment by gregoryh325** [comment]
That's not true---waiting. I did wait on several videos. They don't play and I get a 403 popup box

**Comment by Shadowmaster16** [comment]
> That's not true---waiting. I did wait on several videos. They don't play and I get a 403 error popup box

No, just wait 1-3 minutes for a video. It tries several variants and shows a 403 error multiple times, but eventually it plays the video and saves that.

**Comment by NoMeNoMeNo** [comment]
> It works fine. Start a new video and wait. The program tried different methods by itself. After 4-5 attempts, it played the video. Later, it worked without testing and chose the right playback method.

I think you may have mistaken what the real issue is. 

The problem is that resolution is now capped at 1080P and VP9 is locked out.

The fix will return 4K and VP9 decoding.

**Comment by ACR-Jeff** [comment]
I had 1 403 error on the previous version, Then updated to the new recent version of ST, Now getting 403 loops followed by spinning wheel.

**Comment by mindforger** [comment]
> > That's not true---waiting. I did wait on several videos. They don't play and I get a 403 error popup box
> 
> No, just wait 1-3 minutes for a video. It tries several variants and shows a 403 error multiple times, but eventually it plays the video and saves that.

I can confirm, hitting play a few times fixed it for me too

**Comment by NoMeNoMeNo** [comment]
I just tested 22.79 Beta, and it did not fix the 1080P cap.

To reiterate, 22.79 Beta does NOT fix 4K/VP9.

**Comment by Grannky** [comment]
> > It works fine. Start a new video and wait. The program tried different methods by itself. After 4-5 attempts, it played the video. Later, it worked without testing and chose the right playback method.
> 
> I think you may have mistaken what the real issue is.
> 
> The problem is that resolution is now capped at 1080P and VP9 is locked out.
> 
> The fix will return 4K and VP9 decoding.

I can confirm this, changing resolution and encoding to 1080p avc on video presets removes the 403 as a workaround.

**Comment by BobbyWibowo** [comment]
Changelog for beta 22.79 explicitly said the temp fix is only up to full hd (1080p) for now. Wait further fixes for higher res.

**Comment by Grannky** [comment]
> Changelog for beta 22.79 explicitly said the temp fix is only up to full hd (1080p) for now. Wait further fixes for higher res.

I think the main problem is that the update in itself does not force 1080p avc default, until the issue is resolved, so people are just applying the update and not looking at notes and in my case I assumed it was the supported resolution and encoding was being forced upon patching.

**Comment by NoMeNoMeNo** [comment]
> Changelog for beta 22.79 explicitly said the temp fix is only up to full hd (1080p) for now. Wait further fixes for higher res.

I understood that, but in the past I believe “FULLHD” was the terminology used to signify 4K as opposed to “HD” which meant 1080P.

.

**Comment by albino1** [comment]
They acknowledged the new problem on their patreon and said they are currently working on a fix:

https://www.patreon.com/smarttube/posts

**Comment by NoMeNoMeNo** [comment]
> @NoMeNoMeNo HD = 720p FullHD = 1080p UltraHD = 4K/8K
> 
> https://en.wikipedia.org/w/index.php?title=Ultra-high-definition_television


That's understood.

I don't think I've ever seen a changelog using the term “UltraHD”, but I could be wrong.

.

**Comment by Grannky** [comment]
> > @NoMeNoMeNo HD = 720p FullHD = 1080p UltraHD = 4K/8K
> > https://en.wikipedia.org/w/index.php?title=Ultra-high-definition_television
> 
> That's understood.
> 
> I don't think I've ever seen a changelog using the term “UltraHD”, but I could be wrong.
> 
> .

It's kind of understandable what the term UHD is, it's a term referring to above the standardised 1080 for FHD, 4K , 8K and coming in 2060 26K.

The term UHD is a temporal placeholder for things above 1080p until 4K becomes standard in around 10 years.

Then 1080p becomes 720p
720 becomes 480p ( or whatever )

Around, Around we go....

**Comment by lde** [comment]
Hi
Here more details about Issue on my side 

`07-31 22:05:29.107 14251 14365 E ExoPlayerImplInternal: Source error.
07-31 22:05:29.107 14251 14365 E ExoPlayerImplInternal: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
07-31 22:05:29.107 14251 14365 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:356)
07-31 22:05:29.107 14251 14365 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257)
07-31 22:05:29.107 14251 14365 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
07-31 22:05:29.107 14251 14365 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:77)
07-31 22:05:29.107 14251 14365 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394)
07-31 22:05:29.107 14251 14365 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-31 22:05:29.107 14251 14365 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-31 22:05:29.107 14251 14365 E ExoPlayerImplInternal: 	at java.lang.Thread.run(Thread.java:923)
`

After 3 Burger notification video start without doing anything.

Occurs only once by app Lunch


Impact on usage is low.

Thanks to devs. I just subscribed to Patreon : https://www.patreon.com/smarttube/
Take Care.
Great App !

**Comment by lde** [comment]
22.79 version of the app fixed the issue on my side.

**Comment by ACR-Jeff** [comment]
> 22.79 version of the app fixed the issue on my side.

Yes came here to say the same, Thank you to the devs. Awesome as always.

**Comment by GreenBeanMech** [comment]
22.80 still giving 403 with this video on my Nvidia Shield, any other platforms feel free to test

[It has a warning before that i'm wondering isn't being handled correctly](https://www.youtube.com/watch?v=_O-S3xGzjAM&rco=1)

**Comment by hiroober** [comment]
22.81 started to get error 403 from last night. I'm so sad...

**Comment by lde** [comment]
I'm not able to reproduce error on 22.80 or 22.81.
I seems google is doing testing on cohorts of accounts.

**Comment by allenzhang3305** [comment]
22.80  same error

**Comment by Katerle** [comment]
22.81 Stable and Beta, FireTV, logged in, error 403 on first vid after starting app, it takes a litte time (around 30 seconds), then vid plays. After that all others no problem. Short: 1st vid after app-start, be patient, then it works.

**Comment by Sahilluci** [comment]
I had same issue but I will check

**Comment by LeEcHeR123** [comment]
22.95 on Nvidia Shield. Error appears a lot, it tries to apply the fix but the error mostly keeps returning in a loop. I don't know if it's related to the 403 error but videos take a very long time to load and sometimes don't load at all.
